package com.epam.jmp.jdbc;

public class Constants {

	final static String DRIVER_NAME = "org.h2.Driver";
	final static String DB_URL = "jdbc:h2:tcp://localhost/~/test";
	final static String DB_USER_NAME = "sa";
	final static String DB_USER_PASSWORD = "";

	final static String SQL_DELETE_TABLE_USERS = "DROP TABLE IF EXISTS USERS";
	final static String SQL_DELETE_TABLE_FRIENDSHIPS = "DROP TABLE IF EXISTS FRIENDSHIPS";
	final static String SQL_DELETE_TABLE_POSTS = "DROP TABLE IF EXISTS POSTS";
	final static String SQL_DELETE_TABLE_LIKES = "DROP TABLE IF EXISTS LIKES";

	final static String SQL_CREATE_TABLE_USERS = "CREATE TABLE IF NOT EXISTS USERS(ID INT AUTO_INCREMENT PRIMARY KEY, USERNAME VARCHAR(255), SURENAME VARCHAR(255), BIRTHDATE TIMESTAMP)";
	final static String SQL_CREATE_TABLE_FRIENDSHIPS = "CREATE TABLE IF NOT EXISTS FRIENDSHIPS(USERID1 INT, USERID2 INT, FRIENDSHIPDATE TIMESTAMP)";
	final static String SQL_CREATE_TABLE_POSTS = "CREATE TABLE IF NOT EXISTS POSTS(ID INT AUTO_INCREMENT PRIMARY KEY, USERID INT, TEXT VARCHAR(255), POSTDATE TIMESTAMP)";
	final static String SQL_CREATE_TABLE_LIKES = "CREATE TABLE IF NOT EXISTS LIKES(POSTID INT, USERID INT, LIKEDATE TIMESTAMP)";

	final static String SQL_INSERT_USER = "INSERT INTO USERS(USERNAME, SURENAME, BIRTHDATE) VALUES(?,?,?)";
	final static String SQL_INSERT_FRIENDSHIP = "INSERT INTO FRIENDSHIPS(USERID1, USERID2, FRIENDSHIPDATE) VALUES(?,?,?)";
	final static String SQL_INSERT_POST = "INSERT INTO POSTS(USERID, TEXT, POSTDATE) VALUES(?,?,?)";
	final static String SQL_INSERT_LIKE = "INSERT INTO LIKES(POSTID, USERID, LIKEDATE) VALUES(?,?,?)";

	final static String USER_BIRTHDAY_START_DATE = "1950-01-01 00:00:00";
	final static String USER_BIRTHDAY_END_DATE = "1998-09-09 00:00:00";
	final static String FRIENDSHIP_START_DATE = "1990-01-01 00:00:00";
	final static String SEPT_9_2016_DATE = "2016-09-09 00:00:00";
	final static String POST_START_DATE = "1990-01-01 00:00:00";
	final static String LIKE_START_DATE = "2015-01-01 00:00:00";
	final static String LIKE_END_DATE = "2015-12-31 00:00:00";
	
	final static String alph = "abcdefghijklmnopqrstuvwxyz";

	final static String SQL_SELECT_USERS = "SELECT DISTINCT USERS.ID AS USER_ID,"
												+ " USERS.USERNAME AS USER_NAME,"
												+ " COUNT(LIKES.USERID) AS LIKES_NUMBER"
											+ " FROM ("
												+ "(LIKES INNER JOIN USERS"
												+ " ON  LIKES.USERID =  USERS.ID AND  LIKEDATE BETWEEN ? AND ?)"
												+ " INNER JOIN (SELECT USERID1 AS USER_ID, COUNT(*) AS TOTAL "
												+ " FROM FRIENDSHIPS GROUP BY USERID1 HAVING TOTAL  > ?)"
												+ " ON USER_ID = USERS.ID)"
											+ " GROUP BY USER_ID HAVING LIKES_NUMBER > ?";	
	
	final static String QUERY_LIKE_START_DATE = "2015-03-01 00:00:00";
	final static String QUERY_LIKE_END_DATE = "2015-03-31 23:59:00";

}
